name: stem_microservice_beat
description: Beat scheduler for the Stem microservice example.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  yaml: ^3.1.2
  stem:
    path: ../../..

dev_dependencies:
  lints: ^6.0.0
