version: "3"

vars:
  COVERAGE_BADGE: ../../tool/coverage/coverage_badge.dart

tasks:
  test:
    desc: Run stem package tests.
    cmds:
      - dart test --fail-fast

  coverage:
    desc: Run stem package coverage workflow.
    cmds:
      - dart test --exclude-tags soak --fail-fast --coverage=coverage
      - dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib
      - dart run {{.COVERAGE_BADGE}} --lcov coverage/lcov.info --out coverage/coverage.json --min 80
