name: stem_routing_parity_example
description: Demonstrates routing priority, broadcast, and multi-queue workers.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  stem:
    path: ../..
