name: stem_and_friends
publish_to: none
environment:
  sdk: ">=3.10.0 <4.0.0"
workspace:
  - packages/stem
  - packages/stem_builder
  - packages/stem_sqlite
  - packages/stem_flutter
  - packages/stem_flutter_sqlite
  - packages/stem_memory
  - packages/stem_adapter_tests
  - packages/stem_redis
  - packages/stem_postgres
  - packages/stem_cli
dev_dependencies:
  coverage: ^1.15.0
  yaml: ^3.1.3
  very_good_analysis: ^10.0.0
