services:
  redis:
    image: quay.io/opstree/redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    restart: unless-stopped

  enqueuer:
    build:
      context: ../../..
      dockerfile: examples/microservice/enqueuer/Dockerfile
      target: dev
    env_file:
      - .env
    environment:
      PORT: ${PORT:-8081}
    ports:
      - "${PORT:-8081}:8081"
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    build:
      context: ../../..
      dockerfile: examples/microservice/worker/Dockerfile
      target: dev
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis-data:
