# syntax=docker/dockerfile:1

FROM dart:stable AS build
WORKDIR /app
COPY . .
WORKDIR /app/examples/email_service
RUN dart pub get
RUN dart compile exe bin/enqueuer.dart -o /app/build/enqueuer

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=build /app/build/enqueuer /app/enqueuer
ENV PORT=8082
EXPOSE 8082
ENTRYPOINT ["/app/enqueuer"]
