version: "3.9"

services:
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"

  enqueuer:
    build:
      context: ../..
      dockerfile: examples/email_service/Dockerfile.enqueuer
    env_file:
      - .env.example
    environment:
      PORT: ${PORT:-8082}
    ports:
      - "${PORT:-8082}:8082"
    depends_on:
      - redis
      - mailhog

  worker:
    build:
      context: ../..
      dockerfile: examples/email_service/Dockerfile.worker
    env_file:
      - .env.example
    depends_on:
      - redis
      - mailhog
