services:
  postgres:
    build:
      context: ../..
      dockerfile: docker/testing/postgres/Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stem_test
    command: ["postgres", "-c", "ssl=on", "-c", "ssl_cert_file=/etc/postgres/certs/server.crt", "-c", "ssl_key_file=/etc/postgres/certs/server.key", "-c", "ssl_ca_file=/etc/postgres/certs/root.crt"]
    ports:
      - "65432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "56379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
