services:
  redis:
    image: quay.io/opstree/redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  enqueuer:
    build:
      context: ../..
      dockerfile: examples/microservice/enqueuer/Dockerfile
    env_file:
      - .env.example
    environment:
      PORT: ${PORT:-8081}
    ports:
      - "${PORT:-8081}:8081"
    depends_on:
      - redis

  worker:
    build:
      context: ../..
      dockerfile: examples/microservice/worker/Dockerfile
    env_file:
      - .env.example
    depends_on:
      - redis
