name: stem_rate_limit_delay_demo
description: Demonstrates delayed delivery with priority clamping and Redis-backed rate limiting.
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  stem:
    path: ../..
  redis: ^4.0.0

dev_dependencies:
  lints: ^6.0.0
