name: stem_monolith_example
description: Simple monolithic Stem deployment with in-memory adapters.
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  stem:
    path: ../..

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
