name: stem_flutter_sqlite
description: SQLite adapter helpers for Flutter-hosted Stem runtimes.
version: 0.1.0
repository: https://github.com/kingwill101/stem
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  stem: ">=0.2.1 <0.3.0"
  stem_flutter: ">=0.1.0 <0.2.0"
  stem_sqlite: ">=0.1.2 <0.2.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: false
