name: stem_microservice_worker
description: Dedicated worker process consuming Stem tasks via Redis.
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  stem:
    path: ../../..

dev_dependencies:
  lints: ^6.0.0
