name: stem_flutter
description: Flutter integration helpers for mobile-friendly Stem runtimes.
version: 0.1.0
repository: https://github.com/kingwill101/stem
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  stem: ">=0.2.1 <0.3.0"
  time_machine2: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: false
