name: stem_encrypted_worker
publish_to: 'none'
description: Worker that decrypts payloads after pulling from the broker.

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cryptography: ^2.5.0
  stem:
    path: ../../..
  stem_redis:
    path: ../../../../stem_redis

dev_dependencies:
  lints: ^6.0.0
