version: "3"

tasks:
  test:
    desc: Run stem_cli package tests.
    cmds:
      - dart test --fail-fast

  test-multi:
    desc: Run stem_cli tests with multi-worker coverage enabled.
    cmds:
      - STEM_CLI_RUN_MULTI=true dart test --fail-fast

  coverage:
    desc: Run stem_cli package coverage workflow.
    cmds:
      - STEM_CLI_RUN_MULTI=true dart test --fail-fast --coverage=coverage
      - dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib
      - dart run ../../tool/coverage/coverage_badge.dart --lcov coverage/lcov.info --out coverage/coverage.json --min 80
