name: stem_redis_postgres_worker
publish_to: 'none'
description: Worker using Redis broker and Postgres result backend.

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  stem:
    path: ../../..
  stem_redis:
    path: ../../../../stem_redis
  stem_postgres:
    path: ../../../../stem_postgres

dev_dependencies:
  lints: ^6.0.0
