name: stem_annotated_workflows
description: Example app using annotated Stem workflows and tasks.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  stem:
    path: ../..

dev_dependencies:
  build_runner: ^2.10.5
  stem_builder:
    path: ../../../stem_builder

dependency_overrides:
  stem:
    path: ../..
  stem_memory:
    path: ../../../stem_memory
