/// Durable state for one concurrently invoked script checkpoint.
enum WorkflowConcurrentStepStatus {
  /// The handler has been admitted but has not completed.
  pending,

  /// The handler currently owns an execution lease and is running.
  running,

  /// The handler requested a durable sleep or event wait.
  suspended,

  /// A timer or event delivered the resume payload.
  ready,

  /// The handler returned and its value is durable.
  completed,

  /// The handler failed. The owning run decides whether to retry/fail.
  failed,
}

/// A durable record scoped to one concurrent checkpoint invocation.
///
/// `invocationId` is generated by the runtime from the branch path and the
/// invocation ordinal. It must not be derived from [stepName] alone: two
/// branches are explicitly allowed to call a local step with the same name.
class WorkflowConcurrentStepRecord {
  const WorkflowConcurrentStepRecord({
    required this.runId,
    required this.invocationId,
    required this.branch,
    required this.stepName,
    required this.stepIndex,
    required this.iteration,
    required this.revision,
    required this.status,
    required this.executionId,
    required this.updatedAt,
    this.value,
    this.suspensionData,
    this.error,
    this.stack,
  });

  final String runId;
  final String invocationId;
  final String branch;
  final String stepName;
  final int stepIndex;
  final int iteration;
  /// Monotonically increasing version used for compare-and-set writes.
  final int revision;
  final WorkflowConcurrentStepStatus status;
  /// Fencing token of the execution that owns running-state mutations.
  final String executionId;
  final Object? value;
  final Map<String, Object?>? suspensionData;
  final String? error;
  final String? stack;
  final DateTime updatedAt;

  Map<String, Object?> toJson() => {
    'runId': runId,
    'invocationId': invocationId,
    'branch': branch,
    'stepName': stepName,
    'stepIndex': stepIndex,
    'iteration': iteration,
    'revision': revision,
    'status': status.name,
    'executionId': executionId,
    if (value != null) 'value': value,
    if (suspensionData != null) 'suspensionData': suspensionData,
    if (error != null) 'error': error,
    if (stack != null) 'stack': stack,
    'updatedAt': updatedAt.toIso8601String(),
  };
}
