import 'dart:convert';

/// Stable logical identity of a checkpoint, separate from execution order.
///
/// Execution claim IDs identify attempts; this ID survives those attempts.
extension type const StepInvocationId(String value) {
  /// Encodes a branch path, local checkpoint name, and iteration without
  /// delimiter collisions. Replaying the same logical call yields the same ID.
  factory StepInvocationId.scoped({
    required List<String> branchPath,
    required String stepName,
    required int iteration,
  }) {
    if (stepName.isEmpty || iteration < 0) {
      throw ArgumentError(
        'A step name and non-negative iteration are required.',
      );
    }
    return StepInvocationId(jsonEncode([branchPath, stepName, iteration]));
  }
}

/// Durable state for one concurrently invoked script checkpoint.
enum WorkflowConcurrentStepStatus {
  /// The handler has been admitted but has not completed.
  pending,

  /// The handler currently owns an execution lease and is running.
  running,

  /// The handler requested a durable sleep or event wait.
  suspended,

  /// A timer or event delivered the resume payload.
  ready,

  /// The handler returned and its value is durable.
  completed,

  /// The handler failed. The owning run decides whether to retry/fail.
  failed,
}

/// A durable record scoped to one concurrent checkpoint invocation.
///
/// `invocationId` is generated by the runtime from the branch path, checkpoint
/// name, and iteration. It must not be derived from [stepName] alone: two
/// branches are explicitly allowed to call a local step with the same name.
class WorkflowConcurrentStepRecord {
  /// Creates an immutable snapshot of JSON-compatible durable state.
  WorkflowConcurrentStepRecord({
    required this.runId,
    required this.invocationId,
    required this.branch,
    required this.stepName,
    required this.stepIndex,
    required this.iteration,
    required this.revision,
    required this.status,
    required this.executionId,
    required this.updatedAt,
    Object? value,
    Map<String, Object?>? suspensionData,
    this.error,
    this.stack,
  }) : value = _freezeJson(value),
       suspensionData = suspensionData == null
           ? null
           : _freezeJson(suspensionData)! as Map<String, Object?> {
    if (runId.isEmpty ||
        invocationId.isEmpty ||
        stepName.isEmpty ||
        executionId.isEmpty ||
        stepIndex < 0 ||
        iteration < 0 ||
        revision < 1) {
      throw ArgumentError(
        'Invalid concurrent checkpoint identity or revision.',
      );
    }
  }

  /// Decodes the canonical representation used by every storage adapter.
  factory WorkflowConcurrentStepRecord.fromJson(Map<String, Object?> json) {
    String string(String key) {
      final value = json[key];
      if (value is! String) {
        throw FormatException('Invalid concurrent checkpoint field: $key');
      }
      return value;
    }

    int integer(String key) {
      final value = json[key];
      if (value is! int) {
        throw FormatException('Invalid concurrent checkpoint field: $key');
      }
      return value;
    }

    try {
      return WorkflowConcurrentStepRecord(
        runId: string('runId'),
        invocationId: string('invocationId'),
        branch: string('branch'),
        stepName: string('stepName'),
        stepIndex: integer('stepIndex'),
        iteration: integer('iteration'),
        revision: integer('revision'),
        status: WorkflowConcurrentStepStatus.values.byName(string('status')),
        executionId: string('executionId'),
        updatedAt: DateTime.parse(string('updatedAt')),
        value: json['value'],
        suspensionData: (json['suspensionData'] as Map?)
            ?.cast<String, Object?>(),
        error: json['error'] as String?,
        stack: json['stack'] as String?,
      );
      // Normalize constructor validation errors at the decoding boundary.
      // ignore: avoid_catching_errors
    } on ArgumentError catch (error) {
      throw FormatException('Invalid concurrent checkpoint: $error');
      // Normalize invalid JSON field types at the decoding boundary.
      // ignore: avoid_catching_errors
    } on TypeError catch (error) {
      throw FormatException('Invalid concurrent checkpoint: $error');
    }
  }

  /// Owning workflow run.
  final String runId;

  /// Serialized stable logical identity, never a freshly generated attempt ID.
  final String invocationId;

  /// Typed view of the persisted invocation identity.
  StepInvocationId get identity => StepInvocationId(invocationId);

  /// Encoded branch scope; empty for the root script.
  final String branch;

  /// Local checkpoint name within its branch.
  final String stepName;

  /// Replay traversal ordinal, not completion order or persistence identity.
  final int stepIndex;

  /// Versioned invocation number for repeated checkpoints.
  final int iteration;

  /// Monotonically increasing version used for compare-and-set writes.
  final int revision;

  /// Durable checkpoint state.
  final WorkflowConcurrentStepStatus status;

  /// Fencing token of the execution that owns running-state mutations.
  final String executionId;

  /// Encoded result; completed status distinguishes a null result from absence.
  final Object? value;

  /// Independent timer/event request and any delivered payload.
  final Map<String, Object?>? suspensionData;

  /// Persisted failure description, if any.
  final String? error;

  /// Persisted failure stack, if any.
  final String? stack;

  /// Timestamp of this revision.
  final DateTime updatedAt;

  /// Validates CAS and immutable identity against an atomically read snapshot.
  ///
  /// A missing expected revision (or zero) means insert only. Adapters must
  /// also validate the owning run's active execution lease in the transaction.
  void validateTransition(
    WorkflowConcurrentStepRecord? previous, {
    required int? expectedRevision,
    String? checkpointName,
  }) {
    validateCheckpoint(checkpointName);
    if ((previous?.revision ?? 0) != (expectedRevision ?? 0) ||
        revision != (previous?.revision ?? 0) + 1) {
      throw StateError('Concurrent checkpoint revision conflict.');
    }
    if (previous?.status == WorkflowConcurrentStepStatus.completed) {
      throw StateError('Completed concurrent checkpoint is immutable.');
    }
    if (previous != null &&
        (previous.runId != runId ||
            previous.invocationId != invocationId ||
            previous.branch != branch ||
            previous.stepName != stepName ||
            previous.stepIndex != stepIndex ||
            previous.iteration != iteration)) {
      throw StateError('Concurrent checkpoint identity cannot change.');
    }
  }

  /// Rejects checkpoint projections on non-completed records.
  void validateCheckpoint(String? name) {
    if (name != null &&
        (name.isEmpty || status != WorkflowConcurrentStepStatus.completed)) {
      throw StateError(
        'Only completed records can project a named checkpoint.',
      );
    }
  }

  /// Encodes a snapshot without losing a completed null result.
  Map<String, Object?> toJson() => {
    'runId': runId,
    'invocationId': invocationId,
    'branch': branch,
    'stepName': stepName,
    'stepIndex': stepIndex,
    'iteration': iteration,
    'revision': revision,
    'status': status.name,
    'executionId': executionId,
    'value': value,
    if (suspensionData != null) 'suspensionData': suspensionData,
    if (error != null) 'error': error,
    if (stack != null) 'stack': stack,
    'updatedAt': updatedAt.toIso8601String(),
  };
}

Object? _freezeJson(Object? value) {
  if (value == null || value is String || value is bool || value is int) {
    return value;
  }
  if (value is double && value.isFinite) return value;
  if (value is List) {
    return List<Object?>.unmodifiable(value.map(_freezeJson));
  }
  if (value is Map) {
    return Map<String, Object?>.unmodifiable({
      for (final entry in value.entries)
        _jsonKey(entry.key): _freezeJson(entry.value),
    });
  }
  throw ArgumentError('Durable checkpoints require JSON-compatible values.');
}

String _jsonKey(Object? key) {
  if (key is String) return key;
  throw ArgumentError('Durable checkpoint maps require string keys.');
}
