version: '3.9'

services:
  redis:
    image: redis:7.2
    ports:
      - '6379:6379'
    command: ["redis-server", "--appendonly", "yes"]

  api:
    build:
      context: ../..
      dockerfile: examples/image_processor/Dockerfile.api
    env_file:
      - .env
    environment:
      PORT: ${PORT:-8083}
    ports:
      - "${PORT:-8083}:8083"
    depends_on:
      - redis

  worker:
    build:
      context: ../..
      dockerfile: examples/image_processor/Dockerfile.worker
    env_file:
      - .env
    depends_on:
      - redis
