name: stem_image_processor_example
description: Image thumbnail generation example using Stem task queue.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  image: ^4.1.3
  http: ^1.1.0
  path: ^1.8.3
  stem:
    path: ../..
