name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.5.0

      - name: Fetch dependencies
        run: dart pub get

      - name: Run quality checks
        run: tool/quality/run_quality_checks.sh
        env:
          STEM_CHAOS_REDIS_URL: redis://127.0.0.1:6379/15
          COVERAGE_THRESHOLD: 60

      - name: Validate OpenSpec changes
        run: |
          if command -v openspec >/dev/null 2>&1; then
            openspec validate --strict
          else
            echo 'openspec CLI not available; skipping validation'
          fi

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Docusaurus dependencies
        working-directory: .site
        run: npm install

      - name: Build docs
        working-directory: .site
        run: npm run build

      - name: Monolith example smoke test
        run: dart run scripts/test_monolith.dart

      - name: Microservice smoke test
        run: dart run scripts/test_microservice.dart
