name: Security Scan

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  vulnerability-scan:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: kingwill101/gha-dart@v2
        with:
          sdk: stable

      - name: Run vulnerability scan
        env:
          TRIVY_SEVERITY: CRITICAL,HIGH
          TRIVY_FAIL_ON: '1'
        run: ./scripts/security/run_vulnerability_scan.sh
